[package]
name = "learn_algorithms_with_rust"
version = "0.1.0"
authors = ["IceyBlackTea <One_Random@outlook.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.0"
